name: Deploy to VPS

on:
  push:
    branches:
      - production
    paths:
      - 'wemet-frontend/**'

  workflow_dispatch:
    inputs:
      deploy_message:
        description: 'Deployment message'
        required: true
        default: 'Manual deployment'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout frontend repository
      uses: actions/checkout@v2
      with:
        repository: musta20/wemet-frontend
        ref: production

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
        npm ci

    - name: Build frontend
      run: |
        npm run build

    - name: Checkout backend repository
      uses: actions/checkout@v2
      with:
        repository: musta20/wemetServer
        ref: upgrade-and-refactor
        path: wemetServer

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.VPS_DIGITALOCIAN_PRIVATE_KEY }}
        known_hosts: ${{ secrets.VPS_KNOWN_HOSTS }}

    - name: Deploy to VPS
      env:
        HOST: ${{ secrets.VPS_HOST }}
        USER: ${{ secrets.VPS_USERNAME }}
        DIR: ${{ secrets.VPS_DIR }}
      run: |
        scp -r wemetServer/* ${USER}@${HOST}:${DIR}
        scp -r wemet-frontend/dist/* ${USER}@${HOST}:${DIR}
        ssh ${USER}@${HOST} "cd ${DIR} && npm install && pm2 restart wemet"