name: Deploy to VPS

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout wemet-frontend repo
        uses: actions/checkout@v3

      - name: Checkout wemetServer repo
        uses: actions/checkout@v3
        with:
          repository: musta20/wemetServer
          ref: upgrade-and-refactor
          path: wemetServer

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' 

      - name: Build React app
        run: |
          npm install
          npm run build

      - name: COPY WEMETSERVER REPO TO VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_DIGITALOCIAN_PRIVATE_KEY }}
          source: "wemetServer"
          target: ${{ secrets.VPS_DIR }}

      - name: COPY DIST SERVER REPO TO VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_DIGITALOCIAN_PRIVATE_KEY }}
          source: "./dist"
          target: ${{ secrets.VPS_DIR }}/wemetServer

      # - name: Deploy to VPS
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.VPS_HOST }}
      #     username: ${{ secrets.VPS_USERNAME }}
      #     key: ${{ secrets.VPS_DIGITALOCIAN_PRIVATE_KEY }}
      #     script: |
      #       cd ${{ secrets.VPS_DIR }}
      #       pm2 restart wemet
     # - name: Copy wemetServer to VPS
     #   run: |
     #     scp -r wemetServer ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }}:${{ secrets.VPS_DIR }}/wemetServer

     # - name: Copy React build to VPS
     #   run: |
     #     scp -r wemet-frontend/dist ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }}:${{ secrets.VPS_DIR }}/wemetServer/ 

     # - name: Install dependencies and restart server on VPS
     #   run: |
     #     ssh ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} "
     #       cd ${{ secrets.VPS_DIR }}/wemetServer &&
     #       npm install &&
     #       pm2 restart wemetServer || pm2 start index.js --name wemetServer
     #     "