name: Deploy to VPS

on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout frontend repository
      uses: actions/checkout@v2
      with:
        repository: musta20/wemet-frontend
        ref: production

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
        npm ci

    - name: Build frontend
      run: |
        npm run build

    - name: Checkout backend repository
      uses: actions/checkout@v2
      with:
        repository: musta20/wemetServer
        ref: upgrade-and-refactor
        path: wemetServer

    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_DIGITALOCIAN_PRIVATE_KEY }}
        port: 22 # Adjust if needed
        script: |
          cd ${{ secrets.VPS_DIR }}
          scp -r wemetServer/* ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }}:${{ secrets.VPS_DIR }}
          scp -r wemet-frontend/dist/* ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }}:${{ secrets.VPS_DIR }}
          ssh ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} "cd ${{ secrets.VPS_DIR }} && npm install && pm2 restart wemet"